language: node_js
node_js:
  - "0.10"
  - "0.12"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run backend > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --with-coverage --output
  - node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
#after_success:           # If you have in Environment variable set COVERALLS_REPO_TOKEN
#  - npm run test:report  # – uncomment this lines to enable coverage reports uploading
